apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foundry-idp

resources:
  - namespace.yaml
  - configmap-backend.yaml
  - secret-backend.yaml
  - deployment-postgres.yaml
  - deployment-backend.yaml
  - deployment-worker.yaml
  - deployment-frontend.yaml
  - deployment-redis.yaml
  - service-backend.yaml
  - service-frontend.yaml
  - service-redis.yaml
  - ingress.yaml
  - pvc-backend-storage.yaml

# Common labels
commonLabels:
  app.kubernetes.io/name: foundry-idp
  app.kubernetes.io/part-of: foundry-idp
  app.kubernetes.io/managed-by: kustomize

